"""Deterministic replay provider for testing and evaluation experiments."""

from __future__ import annotations

import json
from typing import Any

from acip.core.llm.contracts import (
    FinishReason,
    LLMRequest,
    LLMResponse,
    LLMUsage,
    ProviderAvailability,
)
from acip.core.llm.errors import LLMError

DEFAULT_TRIAGE_RESPONSE = json.dumps(
    {
        "classification": {
            "category": "incident_triage",
            "summary": "Baseline triage analysis generated by replay test double.",
            "confidence": 0.9,
            "initial_severity": "info",
            "reasoning": "Replay double generated valid structured triage response.",
        },
        "entities": [
            {"entity_type": "host", "value": "web01", "role": "target", "context": "Target host"}
        ],
        "indicators": [],
        "evidence_gaps": [],
        "investigation_plan": [
            {"task_type": "log_analysis", "rationale": "Analyze logs", "priority": 1},
            {"task_type": "reporting", "rationale": "Generate report", "priority": 2},
        ],
    }
)


class ReplayProvider:
    """Test double that returns deterministic pre-configured responses or simulated errors."""

    def __init__(
        self,
        *,
        name: str = "replay",
        default_response: str = '{"result": "ok"}',
        canned_responses: dict[str, str] | None = None,
        simulated_errors: list[LLMError] | None = None,
    ) -> None:
        self.name = name
        self.default_response = default_response
        self.canned_responses = dict(canned_responses or {})
        self.simulated_errors = list(simulated_errors or [])
        self.call_history: list[dict[str, Any]] = []

    async def complete(self, request: LLMRequest, model: str) -> LLMResponse:
        self.call_history.append({"request": request, "model": model})

        # Check for simulated errors to pop
        if self.simulated_errors:
            err = self.simulated_errors.pop(0)
            err.provider = self.name
            err.model = model
            raise err

        # Match message content against canned responses (supports substring keys)
        content = self.default_response
        for msg in reversed(request.messages):
            matched = False
            for key, canned in self.canned_responses.items():
                if key in msg.content:
                    content = canned
                    matched = True
                    break
            if matched:
                break

        return LLMResponse(
            content=content,
            usage=LLMUsage(prompt_tokens=10, completion_tokens=10, total_tokens=20),
            finish_reason=FinishReason.STOP,
            model=model,
            provider=self.name,
            latency_ms=5,
        )

    async def probe(self) -> ProviderAvailability:
        return ProviderAvailability(
            available=True,
            message="Replay provider online",
            models=["replay-model"],
        )


__all__ = ["ReplayProvider"]
